# Generated by Django 5.1.2 on 2024-11-20 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.URLField(verbose_name='Image URL')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], verbose_name='Gender')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age (in years)')),
                ('breed', models.CharField(blank=True, max_length=255, null=True, verbose_name='Breed')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight (kg)')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Height (cm)')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Color')),
                ('size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=6, verbose_name='Size')),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('ILL', 'Ill'), ('IN_RECOVERY', 'In Recovery'), ('SPECIAL_CARE', 'Requires Special Care')], default='HEALTHY', verbose_name='Health Status')),
                ('special_needs', models.TextField(blank=True, null=True, verbose_name='Special Needs')),
                ('vaccination_status', models.CharField(choices=[('UP_TO_DATE', 'Up to Date'), ('PARTIAL', 'Partial'), ('NOT_VACCINATED', 'Not Vaccinated')], default='NOT_VACCINATED', verbose_name='Vaccination Status')),
                ('microchip_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Microchip ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('adoption_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Adoption Fee')),
                ('adopt_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('ADOPTED', 'Adopted'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', verbose_name='Adoption Status')),
                ('is_adopted', models.BooleanField(default=False, verbose_name='Is Adopted')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Is Booked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['-created_at'],
            },
        ),
    ]
