# Generated by Django 5.1.2 on 2024-11-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image URL'),
        ),
    ]
