# Generated by Django 5.1.2 on 2024-12-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopter',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='is_verified',
        ),
    ]
