# Generated by Django 5.1.2 on 2024-12-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_remove_customuser_is_admin_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_approved',
        ),
    ]
